#!/usr/bin/env bash

set -euo pipefail

script_dir="$(dirname "${BASH_SOURCE[0]}")"
tmp_dir="${script_dir}/tmp"
mkdir -p "${tmp_dir}"

source "${script_dir}/functions"

export DOCKER_CLI_EXPERIMENTAL=enabled
export AWS_PAGER=""

check_null BUILDKITE_BUILD_NUMBER
check_null BUILDKITE_BRANCH
check_null BUILDKITE_PIPELINE_DEFAULT_BRANCH

tables=()
read_tables
echo "1. Retrieve schemas..."
retrieve_schemas "${tables[@]}"
echo "2. Create database file..."
create_database "${tables[@]}"
echo "3. Build and publish multi-arch images..."
build_and_publish
