#!/usr/bin/env bash

function check_null {
  local var_name="$1"
  local var_value="${!var_name:-}"
  if [[ -z "$var_value" ]]; then
    echo "The environment variable $var_name must be set."
    exit 1
  fi
}

# Read a plugin property of type [array, string] into a Bash array. Buildkite
# exposes a string value at BUILDKITE_PLUGIN_{NAME}_{KEY}, and array values at
# BUILDKITE_PLUGIN_{NAME}_{KEY}_{IDX}.
function read_list_property {
  local prefix="BUILDKITE_PLUGIN_DYNAMODB_IMAGE_${1}"
  local property="${prefix}_0"
  result=()
  if [[ -n ${!property:-} ]]; then
    local i=0
    local property="${prefix}_${i}"
    while [[ -n ${!property:-} ]]; do
      result+=("${!property}")
      i=$((i + 1))
      property="${prefix}_${i}"
    done
  elif [[ -n ${!prefix:-} ]]; then
    result+=("${!prefix}")
  fi
  [[ ${#result[@]} -gt 0 ]] || return 1
}

# Read tables into an array
function read_tables {
  if read_list_property 'TABLES'; then
    for table in "${result[@]}"; do
      tables+=("${table}")
    done
  else
    echo "A list of tables must be provided."
    exit 1
  fi
}

function read_tables_with_output {
  read_tables
  echo "${tables[@]}" 
}